column_dtypes:
  chunk: &id001 !!python/name:meerkat.columns.scalar.pandas.PandasScalarColumn ''
  chunk_id: *id001
  chunk_idx: *id001
  embeddings/cohere/small: !!python/name:meerkat.columns.tensor.numpy.NumPyTensorColumn ''
  file_id: *id001
  filename: *id001
  ntokens: *id001
  similarity: *id001
dtype: !!python/name:meerkat.dataframe.DataFrame ''
len: 7701
state:
  _primary_key: chunk_id
